### ISSUE TITLE
Type safe composition

### ISSUE THREAD

**Issue by andys8** [hipstersmoothie/compose-tiny#18]
The type definition is currently `any => any`. 
https://github.com/hipstersmoothie/compose-tiny/blob/487391d5440f53ea506361c5deef8de7f2323a98/compose-tiny.d.ts#L2

Would be great to have type safety. `(B => C, A => B) => (A => C)`

I was looking into the types of ramda and they use function overloading. Could be a help to make the adaptions.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/118bdba29e0a94778a7e46cb6e33dd26f9ee484c/types/ramda/index.d.ts#L386

**Comment by hipstersmoothie** [comment]
Oh that sounds. Cool I'll look into it!

**Comment by hipstersmoothie** [comment]
@andys8 I think I made it a bit better! with #23

**Comment by andys8** [comment]
Awesome. The resulting type's input is an `any[]`. Can you explain to me, why this is necessary? Again, comparing with Ramda, and they go with a generic instead, so the result takes only the same input as the first composed function.

```ts
function Compose<T1, T2>(
    fn1: (a: T1) => T2,
    fn0: (...args: any[]) => T1
  ): (...arg: any[]) => T2;
```

So could we replace `any[]` with `V`?

**Comment by hipstersmoothie** [comment]
Gotta admit I am a typescript noobie. this is me starting to understand generics. can you point me towards docs on `V`?

**Comment by hipstersmoothie** [comment]
this seems related https://github.com/Microsoft/TypeScript/issues/5453

**Comment by andys8** [comment]
I made a proposal in form of a pull request. Happy to have your feedback, if this wouldn't work out.
